### ISSUE TITLE
compile this and put it in releases please

### ISSUE THREAD

**Issue by PeppoNetwork** [Gopro336/CLEAN_1.5.4_PHOBOS#1]

**Comment by Oecher1** [comment]
> _No description provided._

uh oh raggy retard alert https://github.com/Gopro336/CLEAN_1.5.4_PHOBOS/blob/main/CLEAN_Phobos_1.5.4.jar

**Comment by PeppoNetwork** [comment]
this is not actually clean phobos
its same size as the ratted one!

**Comment by Gopro336** [comment]
It is not the same size as the ratted one. If you download source code from releases the jar is in the zip.

**Comment by PeppoNetwork** [comment]
aight
